/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Ctrl_BD;
import java.awt.Color;
import java.awt.event.KeyEvent;
import static java.lang.System.exit;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author PC
 */
public class VPrincipal extends javax.swing.JFrame {

    Ctrl_BD controladorBD = new Ctrl_BD();

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Icon/icono.png")).getImage());
        etiqueta.setVisible(false);
        if (!controladorBD.conectarBD()) {
            JOptionPane.showMessageDialog(this, "Error al conectar a la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            exit(0);
        }
        controladorBD.conectarMetaData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        etDNI = new javax.swing.JTextField();
        etiqueta = new javax.swing.JLabel();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buenos Días");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Introduzca su DNI para fichar");

        etDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                etDNIFocusLost(evt);
            }
        });
        etDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etDNIKeyTyped(evt);
            }
        });

        etiqueta.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(etDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiqueta)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etDNIKeyTyped
        if (!etDNI.getText().isEmpty()) {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                hacerRegistro();
            }
        }
    }//GEN-LAST:event_etDNIKeyTyped

    private void etDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_etDNIFocusLost
        if (!etDNI.getText().isEmpty()) {
            hacerRegistro();
        }
    }//GEN-LAST:event_etDNIFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controladorBD.cerrarConexion();
    }//GEN-LAST:event_formWindowClosing

    public void hacerRegistro() {
        int i = controladorBD.fichar(etDNI.getText());
        if (i == 1) {
            etiqueta.setVisible(true);
            etiqueta.setText("DNI INCORRECTO");
            etiqueta.setForeground(Color.red);
            
        } else if (i == 2) {
            etiqueta.setVisible(true);
            etiqueta.setText("ADIOS, QUE TENGAS BUEN DIA");
            etiqueta.setForeground(Color.blue);
            
        } else if (i == 3) {
            etiqueta.setVisible(true);
            etiqueta.setText("BIENVENIDO AL TRABAJO");
            etiqueta.setForeground(Color.magenta);

        }
        Timer timer = new Timer();  
                TimerTask tarea = new TimerTask() {  
                    @Override  
                    public void run() {  
  
                        etiqueta.setText("");
                        etDNI.setText("");
                    }  
                };  
                timer.schedule(tarea, 1500);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JTextField etDNI;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
